# Generated by Django 4.2.11 on 2024-04-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
